<a href="https://colab.research.google.com/github/huricane85/FPL-API-Fixture-modeler/blob/main/FB_Tables_%2B_API_Fixtures_%2B_Player_data_attack%2C_defence_and_GK_predictions_30_10_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import scipy
import numpy as np
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
!git clone https://github.com/huricane85/FPL-FB-Ref-tester

Cloning into 'FPL-FB-Ref-tester'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 59 (delta 25), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (59/59), done.

In [5]:
home_table = pd.read_csv('/content/FPL-FB-Ref-tester/PL Home GW6.csv', encoding = "ISO-8859-1", engine='python')
away_table = pd.read_csv('/content/FPL-FB-Ref-tester/PL Away GW6.csv', encoding = "ISO-8859-1", engine='python')

In [6]:
home_table.rename(columns={'ï»¿Squad': 'team'}, inplace=True)
home_table = home_table.replace('Wolverhampton Wanderers','Wolverhampton')
home_table = home_table.replace('Leeds United', 'Leeds Utd')
home_table = home_table.replace('West Ham', 'West Ham Utd')
home_table

               team  MP  W  D  L  GF  ...  Pts  Pts/G   xG  xGA  xGDiff  xGDiff/90
0           Everton   3  2  1  0  11  ...    7   2.33  6.4  3.7     2.7       0.89
1         Liverpool   3  3  0  0   9  ...    9   3.00  8.8  3.2     5.6       1.85
2       Aston Villa   3  2  0  1   8  ...    6   2.00  6.1  6.0     0.2       0.05
3    Leicester City   3  1  0  2   4  ...    3   1.00  2.3  4.2    -1.8      -0.61
4         Tottenham   3  0  2  1   4  ...    2   0.67  4.4  4.5    -0.1      -0.02
5         Leeds Utd   3  1  1  1   5  ...    4   1.33  4.9  3.8     1.1       0.37
6       Southampton   3  2  0  1   6  ...    6   2.00  3.5  3.0     0.5       0.15
7    Crystal Palace   3  1  1  1   3  ...    4   1.33  1.8  4.0    -2.1      -0.71
8            Wolves   3  1  1  1   3  ...    4   1.33  2.9  2.9     0.0       0.01
9           Chelsea   3  1  1  1   7  ...    4   1.33  5.6  4.9     0.7       0.23
10          Arsenal   3  2  0  1   4  ...    6   2.00  2.7  3.3    -0.6      -0.20
11     West Ham Utd   3  1  1  1   5  ...    4   1.33  3.2  3.1     0.2       0.05
12  Manchester City   2  1  0  1   3  ...    3   1.50  2.4  3.5    -1.1      -0.54
13    Newcastle Utd   3  1  0  2   4  ...    3   1.00  3.1  4.9    -1.8      -0.61
14   Manchester Utd   3  0  1  2   2  ...    1   0.33  2.8  5.6    -2.8      -0.93
15         Brighton   3  0  1  2   4  ...    1   0.33  4.5  2.8     1.7       0.57
16        West Brom   3  0  2  1   3  ...    2   0.67  2.4  5.5    -3.1      -1.03
17          Burnley   2  0  0  2   0  ...    0   0.00  1.1  1.3    -0.2      -0.09
18    Sheffield Utd   3  0  1  2   1  ...    1   0.33  3.7  4.6    -0.9      -0.30
19           Fulham   3  0  0  3   1  ...    0   0.00  2.0  6.0    -4.0      -1.33

[20 rows x 14 columns]

In [ ]:
away_table.rename(columns={'ï»¿Squad': 'team'}, inplace=True)
away_table = away_table.replace('Wolverhampton Wanderers','Wolverhampton')
away_table = away_table.replace('Leeds United', 'Leeds Utd')
away_table = away_table.replace('West Ham', 'West Ham Utd')
away_table

In [8]:
home_table1920 = pd.read_csv('/content/FPL-FB-Ref-tester/PL Home 19-20adjusted.csv', encoding = "ISO-8859-1", engine='python')
away_table1920 = pd.read_csv('/content/FPL-FB-Ref-tester/PL Away 19-20adjusted.csv', encoding = "ISO-8859-1", engine='python')

In [ ]:
home_table1920.rename(columns={'ï»¿Squad': 'team'}, inplace=True)
home_table1920 = home_table1920.replace('Wolverhampton Wanderers','Wolverhampton')
home_table1920 = home_table1920.replace('Leeds United', 'Leeds Utd')
home_table1920 = home_table1920.replace('West Ham', 'West Ham Utd')
home_table1920

In [ ]:
homebothyears = home_table.merge(home_table1920, on="team", left_index=True, right_index=True)
homebothyears['MP']=homebothyears['MP_x']+homebothyears['MP_y']
homebothyears['GF']=homebothyears['GF_x']+homebothyears['GF_y']
homebothyears['GA']=homebothyears['GA_x']+homebothyears['GA_y']
homebothyears['H Avg GS'] = homebothyears ['GF'] / homebothyears ['MP']
homebothyears ['H Avg GA'] = homebothyears ['GA'] / homebothyears ['MP']
homebothyears ['Home LA GS'] = homebothyears['H Avg GS'].mean()
homebothyears ['Home LA GA'] = homebothyears['H Avg GA'].mean()
homebothyears ['H AS'] = homebothyears['H Avg GS']/homebothyears ['Home LA GS']
homebothyears ['H DS'] = homebothyears['H Avg GA']/homebothyears ['Home LA GA']
home_table_reduced = homebothyears[['team', 'H AS', 'H DS','Home LA GS']]
home_table_reduced

In [ ]:
away_table1920.rename(columns={'ï»¿Squad': 'team'}, inplace=True)
away_table1920 = away_table1920.replace('Wolverhampton Wanderers','Wolverhampton')
away_table1920 = away_table1920.replace('Leeds United', 'Leeds Utd')
away_table1920 = away_table1920.replace('West Ham', 'West Ham Utd')
away_table1920

In [ ]:
awaybothyears = away_table.merge(away_table1920, on="team", left_index=True, right_index=True)
awaybothyears['MP']=awaybothyears['MP_x']+awaybothyears['MP_y']
awaybothyears['GF']=awaybothyears['GF_x']+awaybothyears['GF_y']
awaybothyears['GA']=awaybothyears['GA_x']+awaybothyears['GA_y']
awaybothyears['A Avg GS'] = awaybothyears ['GF'] / awaybothyears ['MP']
awaybothyears ['A Avg GA'] = awaybothyears ['GA'] / awaybothyears ['MP']
awaybothyears ['Away LA GS'] = awaybothyears['A Avg GS'].mean()
awaybothyears ['Away LA GA'] = awaybothyears['A Avg GA'].mean()
awaybothyears ['A AS'] = awaybothyears['A Avg GS']/awaybothyears ['Away LA GS']
awaybothyears ['A DS'] = awaybothyears['A Avg GA']/awaybothyears ['Away LA GA']
away_table_reduced = awaybothyears[['team', 'A AS', 'A DS','Away LA GS']]
away_table_reduced

In [ ]:
combined_table = pd.merge(home_table_reduced, away_table_reduced, on='team')
combined_table.sort_values('team')
combined_table

In [15]:
from urllib.request import urlopen
from json import loads
from csv import writer


def team_converter(team_id):
    '''Converts a team's ID to their actual name'''
    team_map = {
        1: "Arsenal",
        2: "Aston Villa",
        3: "Brighton",
        4: "Burnley",
        5: "Chelsea",
        6: "Crystal Palace",
        7: "Everton",
        8: "Fulham",
        9: "Leicester City",
        10: "Leeds Utd",
        11: "Liverpool",
        12: "Manchester City",
        13: "Manchester Utd",
        14: "Newcastle Utd",
        15: "Sheffield Utd",
        16: "Southampton",
        17: "Tottenham",
        18: "West Brom",
        19: "West Ham Utd",
        20: "Wolves",
        None: None
    }
    return team_map[team_id]


def position_converter(position):
    '''Converts a player's element_type to their actual position'''
    position_map = {
        1: "Goalkeeper",
        2: "Defender",
        3: "Midfielder",
        4: "Forward"
    }
    return position_map[position]


def main():
    all_data = loads(urlopen("https://fantasy.premierleague.com/api/fixtures/").read())
    fixtures = all_data

    important_data = [
        [
            x["event"],
            team_converter(x["team_h"]),
            team_converter(x["team_a"]),
            x["kickoff_time"],
            
        ]
        for x in fixtures
    ]

    with open("/fixtures_data.csv", "w", encoding="utf-8", newline="") as out:
        headers = ["event","team_h","team_a","kickoff_time"]
        w = writer(out)
        w.writerow(headers)
        w.writerows(important_data)

if __name__ == "__main__":
    main()

In [ ]:
fixtures = pd.read_csv('/fixtures_data.csv', encoding = "ISO-8859-1", engine='python')
fixtures.rename(columns={'event': 'GW'}, inplace=True)
fixtures.rename(columns={'team_h': 'Home Team'}, inplace=True)
fixtures.rename(columns={'team_a': 'Away Team'}, inplace=True)
fixtures = fixtures.replace('Wolverhampton','Wolves')
fixtures

In [17]:
df=fixtures.merge(combined_table,left_on='Home Team',right_on='team',how='inner')

In [ ]:
df

In [19]:
df2=df.merge(combined_table,left_on='Away Team',right_on='team',how='inner')

In [ ]:
df2.sort_values('GW')

In [ ]:
df2.rename(columns={'H AS_x': 'Home AS'}, inplace=True)
df2.rename(columns={'H DS_x': 'Home DS'}, inplace=True)
df2.rename(columns={'A AS_y': 'Away AS'}, inplace=True)
df2.rename(columns={'A DS_y': 'Away DS'}, inplace=True)
df2.rename(columns={'Home LA GS_x': 'Home LA GS'}, inplace=True)
df2.rename(columns={'Away LA GS_x': 'Away LA GS'}, inplace=True)
df2.columns

In [ ]:
df3 = df2[['GW', 'Home Team', 'Away Team', 'kickoff_time', 'Home AS','Home DS','Home LA GS','Away LA GS','Away AS','Away DS']].copy()
df3

In [ ]:
df3['Home Score'] = df3['Home AS']*df3['Away DS']*df3['Home LA GS']
df3['Away Score']=df3['Away AS']*df3['Home DS']*df3['Away LA GS']
fixturesandscores = df3[['GW', 'Home Team','Home Score','Away Score','Away Team']].copy()
fixturesandscores.sort_values('GW')

In [ ]:
gw7 = fixturesandscores[fixturesandscores['GW'] == 7.0]
gw7homescores = gw7[['GW', 'Home Team','Home Score']].copy()
gw7homescores.rename(columns={'Home Score': 'GW7 Projected Goals'}, inplace=True)
gw7homescores.rename(columns={'Home Team': 'Team'}, inplace=True)
gw7awayscores = gw7[['GW', 'Away Team', 'Away Score']].copy()
gw7awayscores.rename(columns={'Away Score': 'GW7 Projected Goals'}, inplace=True)
gw7awayscores.rename(columns={'Away Team': 'Team'}, inplace=True)
gw7projectedscores = gw7homescores.append(gw7awayscores)
gw7projectedscores=gw7projectedscores.drop(columns=['GW'])
gw7projectedscores

In [25]:
gw8 = fixturesandscores[fixturesandscores['GW'] == 8.0]
gw8homescores = gw8[['GW', 'Home Team','Home Score']].copy()
gw8homescores.rename(columns={'Home Score': 'GW8 Projected Goals'}, inplace=True)
gw8homescores.rename(columns={'Home Team': 'Team'}, inplace=True)
gw8awayscores = gw8[['GW', 'Away Team', 'Away Score']].copy()
gw8awayscores.rename(columns={'Away Score': 'GW8 Projected Goals'}, inplace=True)
gw8awayscores.rename(columns={'Away Team': 'Team'}, inplace=True)
gw8projectedscores = gw8homescores.append(gw8awayscores)
gw8projectedscores=gw8projectedscores.drop(columns=['GW'])

In [26]:
gw9 = fixturesandscores[fixturesandscores['GW'] == 9.0]
gw9homescores = gw9[['GW', 'Home Team','Home Score']].copy()
gw9homescores.rename(columns={'Home Score': 'GW9 Projected Goals'}, inplace=True)
gw9homescores.rename(columns={'Home Team': 'Team'}, inplace=True)
gw9awayscores = gw9[['GW', 'Away Team', 'Away Score']].copy()
gw9awayscores.rename(columns={'Away Score': 'GW9 Projected Goals'}, inplace=True)
gw9awayscores.rename(columns={'Away Team': 'Team'}, inplace=True)
gw9projectedscores = gw9homescores.append(gw9awayscores)
gw9projectedscores=gw9projectedscores.drop(columns=['GW'])

In [27]:
gw10 = fixturesandscores[fixturesandscores['GW'] == 10.0]
gw10homescores = gw10[['GW', 'Home Team','Home Score']].copy()
gw10homescores.rename(columns={'Home Score': 'GW10 Projected Goals'}, inplace=True)
gw10homescores.rename(columns={'Home Team': 'Team'}, inplace=True)
gw10awayscores = gw10[['GW', 'Away Team', 'Away Score']].copy()
gw10awayscores.rename(columns={'Away Score': 'GW10 Projected Goals'}, inplace=True)
gw10awayscores.rename(columns={'Away Team': 'Team'}, inplace=True)
gw10projectedscores = gw10homescores.append(gw10awayscores)
gw10projectedscores=gw10projectedscores.drop(columns=['GW'])

In [28]:
gw11 = fixturesandscores[fixturesandscores['GW'] == 11.0]
gw11homescores = gw11[['GW', 'Home Team','Home Score']].copy()
gw11homescores.rename(columns={'Home Score': 'GW11 Projected Goals'}, inplace=True)
gw11homescores.rename(columns={'Home Team': 'Team'}, inplace=True)
gw11awayscores = gw11[['GW', 'Away Team', 'Away Score']].copy()
gw11awayscores.rename(columns={'Away Score': 'GW11 Projected Goals'}, inplace=True)
gw11awayscores.rename(columns={'Away Team': 'Team'}, inplace=True)
gw11projectedscores = gw11homescores.append(gw11awayscores)
gw11projectedscores=gw11projectedscores.drop(columns=['GW'])

In [ ]:
gw7and8 = pd.merge(gw7projectedscores, gw8projectedscores, on='Team')
gw9and10 = pd.merge(gw9projectedscores, gw10projectedscores, on='Team')
gw7to10 = pd.merge(gw7and8, gw9and10, on='Team')
gw7to11 = pd.merge(gw7to10, gw11projectedscores, on='Team')
gw7to11

In [30]:
print(list(gw7to11))

['Team', 'GW7 Projected Goals', 'GW8 Projected Goals', 'GW9 Projected Goals', 'GW10 Projected Goals', 'GW11 Projected Goals']

In [ ]:
cols = ['GW7 Projected Goals', 'GW8 Projected Goals', 'GW9 Projected Goals', 'GW10 Projected Goals', 'GW11 Projected Goals']
for col in cols:
    gw7to11['%s_average' % col] = gw7to11[col].mean()

gw7to11plusaverages = gw7to11
gw7to11plusaverages

In [32]:
print(list(gw7to11plusaverages))

['Team', 'GW7 Projected Goals', 'GW8 Projected Goals', 'GW9 Projected Goals', 'GW10 Projected Goals', 'GW11 Projected Goals', 'GW7 Projected Goals_average', 'GW8 Projected Goals_average', 'GW9 Projected Goals_average', 'GW10 Projected Goals_average', 'GW11 Projected Goals_average']

In [ ]:
gw7to11plusaverages['GW 7 difference']=gw7to11plusaverages['GW7 Projected Goals']/gw7to11plusaverages['GW7 Projected Goals_average']
gw7to11plusaverages['GW 8 difference'] = gw7to11plusaverages['GW8 Projected Goals'] / gw7to11plusaverages['GW8 Projected Goals_average']
gw7to11plusaverages['GW 9 difference'] = gw7to11plusaverages['GW9 Projected Goals'] / gw7to11plusaverages['GW9 Projected Goals_average']
gw7to11plusaverages['GW 10 difference'] = gw7to11plusaverages['GW10 Projected Goals'] / gw7to11plusaverages['GW10 Projected Goals_average']
gw7to11plusaverages['GW 11 difference'] = gw7to11plusaverages['GW11 Projected Goals'] / gw7to11plusaverages['GW11 Projected Goals_average']
gw7to11adjustments = gw7to11plusaverages[['Team', 'GW 7 difference', 'GW 8 difference','GW 9 difference','GW 10 difference','GW 11 difference']]
gw7to11adjustments

In [34]:
from urllib.request import urlopen
from json import loads
from csv import writer


def team_converter(team_id):
    '''Converts a team's ID to their actual name'''
    team_map = {
        1: "Arsenal",
        2: "Aston Villa",
        3: "Brighton",
        4: "Burnley",
        5: "Chelsea",
        6: "Crystal Palace",
        7: "Everton",
        8: "Fulham",
        9: "Leicester City",
        10: "Leeds Utd",
        11: "Liverpool",
        12: "Manchester City",
        13: "Manchester Utd",
        14: "Newcastle utd",
        15: "Sheffield Utd",
        16: "Southampton",
        17: "Tottenham",
        18: "West Brom",
        19: "West Ham Utd",
        20: "Wolverhampton",
        None: None
    }
    return team_map[team_id]


def position_converter(position):
    '''Converts a player's element_type to their actual position'''
    position_map = {
        1: "Goalkeeper",
        2: "Defender",
        3: "Midfielder",
        4: "Forward"
    }
    return position_map[position]


def main():
    all_data = loads(urlopen("https://fantasy.premierleague.com/api/bootstrap-static/").read())
    players = all_data["elements"]

    important_data = [
        [
            x["id"],
            team_converter(x["team"]),
            position_converter(x["element_type"])[0],
            x["web_name"],
            x["now_cost"] / 10,
            x["selected_by_percent"],
            x["goals_scored"],
            x["assists"],
            x["bps"],
            x["ict_index"],
            x["total_points"],  
            x["points_per_game"]
        ]
        for x in players
    ]

    with open("players_data.csv", "w", encoding="utf-8", newline="") as out:
        headers = ["id","team", "pos", "name", "cost", "selected_by_percent", "goals_scored", "assists", "bps", "ict_index","points", "points_per_game"]
        w = writer(out)
        w.writerow(headers)
        w.writerows(important_data)

if __name__ == "__main__":
    main()

In [35]:
import pandas as pd
import scipy
import numpy as np
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib

In [ ]:
import pandas as pd
playerdata = pd.read_csv("/content/players_data.csv")
playerdata

In [37]:
playerdata.rename(columns={'team': 'Team'}, inplace=True)
playerdataattackandmidfield = playerdata.query('pos=="M" | pos=="F"')

In [ ]:
playersteamadjustedattackandmidfield = pd.merge(playerdataattackandmidfield,
                 gw7to11adjustments[['Team','GW 7 difference','GW 8 difference','GW 9 difference','GW 10 difference','GW 11 difference']],
                    on='Team')
playersteamadjustedattackandmidfield

In [39]:
playersteamadjustedattackandmidfield['GW7 Adjusted score'] = playersteamadjustedattackandmidfield['points_per_game'] * playersteamadjustedattackandmidfield['GW 7 difference']
playersteamadjustedattackandmidfield['GW8 Adjusted score'] = playersteamadjustedattackandmidfield['points_per_game'] * playersteamadjustedattackandmidfield['GW 8 difference']
playersteamadjustedattackandmidfield['GW9 Adjusted score'] = playersteamadjustedattackandmidfield['points_per_game'] * playersteamadjustedattackandmidfield['GW 9 difference']
playersteamadjustedattackandmidfield['GW10 Adjusted score'] = playersteamadjustedattackandmidfield['points_per_game'] * playersteamadjustedattackandmidfield['GW 10 difference']
playersteamadjustedattackandmidfield['GW11 Adjusted score'] = playersteamadjustedattackandmidfield['points_per_game'] * playersteamadjustedattackandmidfield['GW 11 difference']
playersteamadjustedattackandmidfield['GW7-11 Adjusted score'] = playersteamadjustedattackandmidfield['GW11 Adjusted score'] + playersteamadjustedattackandmidfield['GW7 Adjusted score'] + playersteamadjustedattackandmidfield['GW8 Adjusted score'] + playersteamadjustedattackandmidfield['GW9 Adjusted score']+ playersteamadjustedattackandmidfield['GW10 Adjusted score']
GWprojectionsattackandmidfield = playersteamadjustedattackandmidfield

In [ ]:
GWprojectionsattackandmidfield.sort_values(by=['GW7-11 Adjusted score'], ascending=False).head(30)

In [ ]:
gw7ga = fixturesandscores[fixturesandscores['GW'] == 7.0]
gw7homescoresagainst = gw7[['GW', 'Home Team','Away Score']].copy()
gw7homescoresagainst.rename(columns={'Away Score': 'GW7 Projected Goals Against'}, inplace=True)
gw7homescoresagainst.rename(columns={'Home Team': 'Team'}, inplace=True)
gw7awayscoresagainst = gw7ga[['GW', 'Away Team', 'Home Score']].copy()
gw7awayscoresagainst.rename(columns={'Home Score': 'GW7 Projected Goals Against'}, inplace=True)
gw7awayscoresagainst.rename(columns={'Away Team': 'Team'}, inplace=True)
gw7projectedscoresagainst = gw7homescoresagainst.append(gw7awayscoresagainst)
gw7projectedscoresagainst=gw7projectedscoresagainst.drop(columns=['GW'])
gw8ga = fixturesandscores[fixturesandscores['GW'] == 8.0]
gw8homescoresagainst = gw8[['GW', 'Home Team','Away Score']].copy()
gw8homescoresagainst.rename(columns={'Away Score': 'GW8 Projected Goals Against'}, inplace=True)
gw8homescoresagainst.rename(columns={'Home Team': 'Team'}, inplace=True)
gw8awayscoresagainst = gw8ga[['GW', 'Away Team', 'Home Score']].copy()
gw8awayscoresagainst.rename(columns={'Home Score': 'GW8 Projected Goals Against'}, inplace=True)
gw8awayscoresagainst.rename(columns={'Away Team': 'Team'}, inplace=True)
gw8projectedscoresagainst = gw8homescoresagainst.append(gw8awayscoresagainst)
gw8projectedscoresagainst=gw8projectedscoresagainst.drop(columns=['GW'])
gw9ga = fixturesandscores[fixturesandscores['GW'] == 9.0]
gw9homescoresagainst = gw9[['GW', 'Home Team','Away Score']].copy()
gw9homescoresagainst.rename(columns={'Away Score': 'GW9 Projected Goals Against'}, inplace=True)
gw9homescoresagainst.rename(columns={'Home Team': 'Team'}, inplace=True)
gw9awayscoresagainst = gw9ga[['GW', 'Away Team', 'Home Score']].copy()
gw9awayscoresagainst.rename(columns={'Home Score': 'GW9 Projected Goals Against'}, inplace=True)
gw9awayscoresagainst.rename(columns={'Away Team': 'Team'}, inplace=True)
gw9projectedscoresagainst = gw9homescoresagainst.append(gw9awayscoresagainst)
gw9projectedscoresagainst=gw9projectedscoresagainst.drop(columns=['GW'])
gw10ga = fixturesandscores[fixturesandscores['GW'] == 10.0]
gw10homescoresagainst = gw10[['GW', 'Home Team','Away Score']].copy()
gw10homescoresagainst.rename(columns={'Away Score': 'GW10 Projected Goals Against'}, inplace=True)
gw10homescoresagainst.rename(columns={'Home Team': 'Team'}, inplace=True)
gw10awayscoresagainst = gw10ga[['GW', 'Away Team', 'Home Score']].copy()
gw10awayscoresagainst.rename(columns={'Home Score': 'GW10 Projected Goals Against'}, inplace=True)
gw10awayscoresagainst.rename(columns={'Away Team': 'Team'}, inplace=True)
gw10projectedscoresagainst = gw10homescoresagainst.append(gw10awayscoresagainst)
gw10projectedscoresagainst=gw10projectedscoresagainst.drop(columns=['GW'])
gw11ga = fixturesandscores[fixturesandscores['GW'] == 11.0]
gw11homescoresagainst = gw11[['GW', 'Home Team','Away Score']].copy()
gw11homescoresagainst.rename(columns={'Away Score': 'GW11 Projected Goals Against'}, inplace=True)
gw11homescoresagainst.rename(columns={'Home Team': 'Team'}, inplace=True)
gw11awayscoresagainst = gw11ga[['GW', 'Away Team', 'Home Score']].copy()
gw11awayscoresagainst.rename(columns={'Home Score': 'GW11 Projected Goals Against'}, inplace=True)
gw11awayscoresagainst.rename(columns={'Away Team': 'Team'}, inplace=True)
gw11projectedscoresagainst = gw11homescoresagainst.append(gw11awayscoresagainst)
gw11projectedscoresagainst=gw11projectedscoresagainst.drop(columns=['GW'])
gw7and8against = pd.merge(gw7projectedscoresagainst, gw8projectedscoresagainst, on='Team')
gw9and10against = pd.merge(gw9projectedscoresagainst, gw10projectedscoresagainst, on='Team')
gw7to10against = pd.merge(gw7and8against, gw9and10against, on='Team')
gw7to11against = pd.merge(gw7to10against, gw11projectedscoresagainst, on='Team')
gw7to11against

In [42]:
print(list(gw7to11against))

['Team', 'GW7 Projected Goals Against', 'GW8 Projected Goals Against', 'GW9 Projected Goals Against', 'GW10 Projected Goals Against', 'GW11 Projected Goals Against']

In [ ]:
cols = ['GW7 Projected Goals Against', 'GW8 Projected Goals Against', 'GW9 Projected Goals Against', 'GW10 Projected Goals Against', 'GW11 Projected Goals Against']
for col in cols:
    gw7to11against['%s_average' % col] = gw7to11against[col].mean()

gw7to11plusaveragesagainst = gw7to11against
gw7to11plusaveragesagainst

In [49]:
print(list(gw7to11plusaveragesagainst))

['Team', 'GW7 Projected Goals Against', 'GW8 Projected Goals Against', 'GW9 Projected Goals Against', 'GW10 Projected Goals Against', 'GW11 Projected Goals Against', 'GW7 Projected Goals Against_average', 'GW8 Projected Goals Against_average', 'GW9 Projected Goals Against_average', 'GW10 Projected Goals Against_average', 'GW11 Projected Goals Against_average', 'GW 7 difference defence', 'GW 8 difference defence', 'GW 9 difference defence', 'GW 10 difference defence', 'GW 11 difference defence']

In [50]:
gw7to11plusaveragesagainst['GW 7 difference defence']=gw7to11plusaveragesagainst['GW7 Projected Goals Against']/gw7to11plusaveragesagainst['GW7 Projected Goals Against_average']
gw7to11plusaveragesagainst['GW 8 difference defence'] = gw7to11plusaveragesagainst['GW8 Projected Goals Against'] / gw7to11plusaveragesagainst['GW8 Projected Goals Against_average']
gw7to11plusaveragesagainst['GW 9 difference defence'] = gw7to11plusaveragesagainst['GW9 Projected Goals Against'] / gw7to11plusaveragesagainst['GW9 Projected Goals Against_average']
gw7to11plusaveragesagainst['GW 10 difference defence'] = gw7to11plusaveragesagainst['GW10 Projected Goals Against'] / gw7to11plusaveragesagainst['GW10 Projected Goals Against_average']
gw7to11plusaveragesagainst['GW 11 difference defence'] = gw7to11plusaveragesagainst['GW11 Projected Goals Against'] / gw7to11plusaveragesagainst['GW11 Projected Goals Against_average']
gw7to11adjustmentsdefence = gw7to11plusaveragesagainst[['Team', 'GW 7 difference defence', 'GW 8 difference defence','GW 9 difference defence','GW 10 difference defence','GW 11 difference defence']]
gw7to11adjustmentsdefence

               Team  ...  GW 11 difference defence
0       Aston Villa  ...                  0.520869
1           Burnley  ...                  1.294731
2            Wolves  ...                  1.844241
3     Newcastle Utd  ...                  1.532876
4     Sheffield Utd  ...                  1.761483
5         Tottenham  ...                  0.885477
6            Fulham  ...                  0.937803
7    Manchester Utd  ...                  0.909575
8         Leeds Utd  ...                  1.051856
9         Liverpool  ...                  0.383549
10      Southampton  ...                  0.848271
11          Chelsea  ...                  1.060678
12   Crystal Palace  ...                  0.748475
13          Everton  ...                  0.460015
14  Manchester City  ...                  0.548152
15         Brighton  ...                  1.325847
16        West Brom  ...                  1.065413
17          Arsenal  ...                  1.128700
18   Leicester City  ...                  0.918129
19     West Ham Utd  ...                  0.773862

[20 rows x 6 columns]

In [ ]:
playerdatagoalkeepers = playerdata.query('pos=="G"')

playerdatagoalkeepers = pd.merge(playerdatagoalkeepers,
                 gw7to11adjustmentsdefence[['Team','GW 7 difference defence','GW 8 difference defence','GW 9 difference defence','GW 10 difference defence','GW 11 difference defence']],
                    on='Team')
playerdatagoalkeepers

In [47]:
playerdatagoalkeepers['GW7 Adjusted score'] = playerdatagoalkeepers['points_per_game'] * playerdatagoalkeepers['GW 7 difference defence']
playerdatagoalkeepers['GW8 Adjusted score'] = playerdatagoalkeepers['points_per_game'] * playerdatagoalkeepers['GW 8 difference defence']
playerdatagoalkeepers['GW9 Adjusted score'] = playerdatagoalkeepers['points_per_game'] * playerdatagoalkeepers['GW 9 difference defence']
playerdatagoalkeepers['GW10 Adjusted score'] = playerdatagoalkeepers['points_per_game'] * playerdatagoalkeepers['GW 10 difference defence']
playerdatagoalkeepers['GW11 Adjusted score'] = playerdatagoalkeepers['points_per_game'] * playerdatagoalkeepers['GW 11 difference defence']
playerdatagoalkeepers['GW7-11 Adjusted score'] = playerdatagoalkeepers['GW11 Adjusted score'] + playerdatagoalkeepers['GW7 Adjusted score'] + playerdatagoalkeepers['GW8 Adjusted score'] + playerdatagoalkeepers['GW9 Adjusted score']+ playerdatagoalkeepers['GW10 Adjusted score']
GWprojectionsgoalkeepers = playerdatagoalkeepers

GWprojectionsgoalkeepers.sort_values(by=['GW7-11 Adjusted score'], ascending=False).head(30)

     id             Team  ... GW11 Adjusted score GW7-11 Adjusted score
15  548          Chelsea  ...            6.894407             27.773328
32  213        Leeds Utd  ...            4.207425             26.280999
28  217   Leicester City  ...            3.856141             25.313130
57  431     West Ham Utd  ...            3.095448             22.512478
54  417        West Brom  ...            3.942029             20.474009
3    12      Aston Villa  ...            3.541907             19.982770
10   96          Burnley  ...            4.402084             18.199371
35  252        Liverpool  ...            1.841034             17.914540
0     8          Arsenal  ...            3.611839             16.377055
47  363      Southampton  ...            3.393084             16.058752
38  278  Manchester City  ...            1.644457             15.348160
41  291   Manchester Utd  ...            2.001064             13.700224
7    70         Brighton  ...            2.386525             13.261060
45  483    Sheffield Utd  ...            4.051411             13.026110
27  516           Fulham  ...            2.063166             12.595557
50  383        Tottenham  ...            2.833525             11.537580
17  128   Crystal Palace  ...            2.095729             10.815891
14  112          Chelsea  ...            2.121356              8.545640
21  157          Everton  ...            1.288041              7.862235
26  186           Fulham  ...            0.937803              5.725253
13  101          Chelsea  ...            1.060678              4.272820
34  245        Liverpool  ...            0.383549              3.732196
56  430     West Ham Utd  ...            0.000000              0.000000
39  538  Manchester City  ...            0.000000              0.000000
40  289   Manchester Utd  ...            0.000000              0.000000
55  429     West Ham Utd  ...            0.000000              0.000000
52  482        Tottenham  ...            0.000000              0.000000
42  305   Manchester Utd  ...            0.000000              0.000000
43  348    Sheffield Utd  ...            0.000000              0.000000
44  350    Sheffield Utd  ...            0.000000              0.000000

[30 rows x 23 columns]

In [51]:
gw7to11defendersworkings = pd.merge(gw7to11adjustmentsdefence, gw7to11adjustments, on='Team')
gw7to11defendersworkings.columns

Index(['Team', 'GW 7 difference defence', 'GW 8 difference defence',
       'GW 9 difference defence', 'GW 10 difference defence',
       'GW 11 difference defence', 'GW 7 difference', 'GW 8 difference',
       'GW 9 difference', 'GW 10 difference', 'GW 11 difference'],
      dtype='object')

In [53]:
gw7to11defendersworkings['GW 7 Defender Adj']=gw7to11defendersworkings['GW 7 difference defence']*0.6 + gw7to11defendersworkings['GW 7 difference']*0.4
gw7to11defendersworkings['GW 8 Defender Adj']=gw7to11defendersworkings['GW 8 difference defence']*0.6 + gw7to11defendersworkings['GW 8 difference']*0.4
gw7to11defendersworkings['GW 9 Defender Adj']=gw7to11defendersworkings['GW 9 difference defence']*0.6 + gw7to11defendersworkings['GW 9 difference']*0.4
gw7to11defendersworkings['GW 10 Defender Adj']=gw7to11defendersworkings['GW 10 difference defence']*0.6 + gw7to11defendersworkings['GW 10 difference']*0.4
gw7to11defendersworkings['GW 11 Defender Adj']=gw7to11defendersworkings['GW 11 difference defence']*0.6 + gw7to11defendersworkings['GW 11 difference']*0.4
gw7to11defendersworkings

               Team  ...  GW 11 Defender Adj
0       Aston Villa  ...            0.925671
1           Burnley  ...            0.960844
2            Wolves  ...            1.259964
3     Newcastle Utd  ...            1.128073
4     Sheffield Utd  ...            1.424141
5         Tottenham  ...            0.982766
6            Fulham  ...            0.781943
7    Manchester Utd  ...            0.855290
8         Leeds Utd  ...            1.055385
9         Liverpool  ...            0.967826
10      Southampton  ...            1.039302
11          Chelsea  ...            1.057149
12   Crystal Palace  ...            0.875250
13          Everton  ...            0.793901
14  Manchester City  ...            0.704013
15         Brighton  ...            1.134817
16        West Brom  ...            0.938638
17          Arsenal  ...            1.031410
18   Leicester City  ...            1.255470
19     West Ham Utd  ...            0.828147

[20 rows x 16 columns]

In [54]:
playerdatadefenders = playerdata.query('pos=="D"')

playerdatadefenders = pd.merge(playerdatadefenders,
                 gw7to11defendersworkings[['Team','GW 7 Defender Adj','GW 8 Defender Adj','GW 9 Defender Adj','GW 10 Defender Adj','GW 11 Defender Adj']],
                    on='Team')
playerdatadefenders

      id          Team  ... GW 10 Defender Adj GW 11 Defender Adj
0      2       Arsenal  ...           0.756426           1.031410
1      3       Arsenal  ...           0.756426           1.031410
2      5       Arsenal  ...           0.756426           1.031410
3      7       Arsenal  ...           0.756426           1.031410
4     10       Arsenal  ...           0.756426           1.031410
..   ...           ...  ...                ...                ...
187  443  West Ham Utd  ...           0.757333           0.828147
188  451  West Ham Utd  ...           0.757333           0.828147
189  452  West Ham Utd  ...           0.757333           0.828147
190  558  West Ham Utd  ...           0.757333           0.828147
191  576  West Ham Utd  ...           0.757333           0.828147

[192 rows x 17 columns]

In [55]:
playerdatadefenders['GW7 Adjusted score'] = playerdatadefenders['points_per_game'] * playerdatadefenders['GW 7 Defender Adj']
playerdatadefenders['GW8 Adjusted score'] = playerdatadefenders['points_per_game'] * playerdatadefenders['GW 8 Defender Adj']
playerdatadefenders['GW9 Adjusted score'] = playerdatadefenders['points_per_game'] * playerdatadefenders['GW 9 Defender Adj']
playerdatadefenders['GW10 Adjusted score'] = playerdatadefenders['points_per_game'] * playerdatadefenders['GW 10 Defender Adj']
playerdatadefenders['GW11 Adjusted score'] = playerdatadefenders['points_per_game'] * playerdatadefenders['GW 11 Defender Adj']
playerdatadefenders['GW7-11 Adjusted score'] = playerdatadefenders['GW11 Adjusted score'] + playerdatadefenders['GW7 Adjusted score'] + playerdatadefenders['GW8 Adjusted score'] + playerdatadefenders['GW9 Adjusted score']+ playerdatadefenders['GW10 Adjusted score']
GWprojectionsdefenders = playerdatadefenders

GWprojectionsdefenders.sort_values(by=['GW7-11 Adjusted score'], ascending=False).head(30)

      id             Team  ... GW11 Adjusted score GW7-11 Adjusted score
52   232          Chelsea  ...            9.514343             40.124504
98   498   Leicester City  ...            7.281729             35.457846
163  389        Tottenham  ...            6.387978             32.920710
123  277  Manchester City  ...            4.576081             30.465100
113  255        Liverpool  ...            4.355216             29.950051
176  414        West Brom  ...            5.631826             29.929150
47   110          Chelsea  ...            6.765755             28.532980
190  558     West Ham Utd  ...            4.389180             26.660620
17    41      Aston Villa  ...            5.554029             26.399976
96   239   Leicester City  ...            5.398523             26.287713
184  435     West Ham Utd  ...            4.306365             26.157590
65   577   Crystal Palace  ...            5.251500             26.000426
20    46      Aston Villa  ...            5.368895             25.519977
187  443     West Ham Utd  ...            4.140735             25.151529
155  369      Southampton  ...            5.612229             23.212956
51   123          Chelsea  ...            5.285746             22.291391
12   494          Arsenal  ...            4.744488             22.153621
90   218   Leicester City  ...            4.394147             21.396976
99   561   Leicester City  ...            4.394147             21.396976
186  442     West Ham Utd  ...            3.478218             21.127284
53   490          Chelsea  ...            4.968601             20.953907
67   155          Everton  ...            3.334385             20.512619
68   156          Everton  ...            3.334385             20.512619
100  195        Leeds Utd  ...            3.482770             20.495313
112  250        Liverpool  ...            2.903477             19.966701
182  530        West Brom  ...            3.754551             19.952767
108  491        Leeds Utd  ...            3.377232             19.874243
103  200        Leeds Utd  ...            3.377232             19.874243
62   486   Crystal Palace  ...            3.938625             19.500320
132  298   Manchester Utd  ...            3.079043             18.978145

[30 rows x 23 columns]